# Generated by Django 4.0.5 on 2022-06-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_month', models.CharField(default='March', max_length=70)),
                ('service_year', models.CharField(default='1996', max_length=70)),
                ('service_day', models.CharField(default='20', max_length=70)),
                ('title', models.CharField(default='None', max_length=70)),
                ('song_leader', models.CharField(default='None', max_length=70)),
                ('announcements', models.CharField(default='None', max_length=70)),
                ('opening_prayer', models.CharField(default='None', max_length=70)),
                ('lords_supper', models.CharField(default='None', max_length=70)),
                ('scripture_reading', models.CharField(default='None', max_length=70)),
                ('closing_prayer', models.CharField(default='None', max_length=70)),
                ('technology', models.CharField(default='None', max_length=70)),
                ('security', models.CharField(default='None', max_length=70)),
                ('day_of_week', models.CharField(choices=[('Sunday', 'Sunday'), ('Wednesday', 'Wednesday')], default='Day', max_length=12)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
